import type { FieldSchema } from "@/modules/engenharia/ui/crud/types";

/** Relatório Gerencial de Serviços (crea_gov_servicos) */
export const SERVICOS_FIELDS: FieldSchema[] = [
  { key: "numero",      label: "Número",       type: "text" },
  { key: "detalhe",     label: "Detalhe",      type: "textarea", full: true },
  { key: "analise",     label: "Análise",      type: "text" },
  { key: "baixa",       label: "Baixa",        type: "text" },
  { key: "boleto",      label: "Boleto",       type: "text" },
  { key: "pagamento",   label: "Pagamento",    type: "text" },
  { key: "cadastro",    label: "Cadastro",     type: "text" },
  { key: "empresa",     label: "Empresa",      type: "text" },
  { key: "contratante", label: "Contratante",  type: "text" },
  { key: "endereco",    label: "Endereço",     type: "textarea", full: true, inList: false },
  { key: "observacao",  label: "Observação",   type: "textarea", full: true, inList: false },
];

/** ART por Bloco (crea_gov_art_bloco) — campos principais (todos os 151 existem na tabela; aqui mostramos os essenciais) */
export const ART_BLOCO_FIELDS: FieldSchema[] = [
  { key: "numero_art",            label: "Nº ART",                 type: "text" },
  { key: "valor_art",             label: "Valor ART",              type: "number" },
  { key: "valor_pago",            label: "Valor Pago",             type: "number", inList: false },
  { key: "responsavel_tecnico",   label: "Responsável Técnico",    type: "text" },
  { key: "titulo_profissional",   label: "Título Profissional",    type: "text", inList: false },
  { key: "rnp",                   label: "RNP",                    type: "text", inList: false },
  { key: "registro",              label: "Registro",               type: "text", inList: false },
  { key: "contratante",           label: "Contratante",            type: "text" },
  { key: "cpf_cnpj_contratante",  label: "CPF/CNPJ Contratante",   type: "text", inList: false },
  { key: "endereco_contrato",     label: "Endereço Contrato",      type: "textarea", full: true, inList: false },
  { key: "endereco_obra",         label: "Endereço Obra",          type: "textarea", full: true, inList: false },
  { key: "contrato",              label: "Contrato",               type: "text", inList: false },
  { key: "celebrado_em",          label: "Celebrado em",           type: "date", inList: false },
  { key: "valor_contrato",        label: "Valor Contrato",         type: "number", inList: false },
  { key: "tipo_contratante",      label: "Tipo Contratante",       type: "text", inList: false },
  { key: "acao_institucional",    label: "Ação Institucional",     type: "text", inList: false },
  { key: "situacao",              label: "Situação",               type: "text" },
  { key: "atendido",              label: "Atendido",               type: "text", inList: false },
  { key: "data_solicitacao",      label: "Data Solicitação",       type: "date", inList: false },
  { key: "data_atendimento",      label: "Data Atendimento",       type: "date", inList: false },
  { key: "motivo",                label: "Motivo",                 type: "textarea", full: true, inList: false },
  { key: "data_inicio",           label: "Data Início",            type: "date" },
  { key: "previsao_termino",      label: "Previsão Término",       type: "date", inList: false },
  { key: "coordenadas",           label: "Coordenadas",            type: "text", inList: false },
  { key: "codigo",                label: "Código",                 type: "text", inList: false },
  { key: "cnpj_cpf_proprietario", label: "CPF/CNPJ Proprietário",  type: "text", inList: false },
  { key: "finalidade",            label: "Finalidade",             type: "text", inList: false },
  { key: "proprietario",          label: "Proprietário",           type: "text", inList: false },
  { key: "ativ_tec_numeros_atos", label: "Atos Tec. (números)",    type: "text", inList: false },
  { key: "ativ_tec_quantidade",   label: "Atos Tec. (qtd)",        type: "number", inList: false },
  { key: "ativ_tec_unidade",      label: "Atos Tec. (unidade)",    type: "text", inList: false },
  { key: "ativ_tec_descricao",    label: "Atos Tec. (descrição)",  type: "textarea", full: true, inList: false },
  { key: "observacoes",           label: "Observações",            type: "textarea", full: true, inList: false },
  { key: "declaracoes",           label: "Declarações",            type: "textarea", full: true, inList: false },
  { key: "entidade_classe",       label: "Entidade de Classe",     type: "text", inList: false },
  { key: "assinaturas",           label: "Assinaturas",            type: "textarea", full: true, inList: false },
  { key: "informacoes",           label: "Informações",            type: "textarea", full: true, inList: false },
];

/** Relatórios CREA (crea_gov_relatorio_crea) */
export const RELATORIO_CREA_FIELDS: FieldSchema[] = [
  { key: "art",                  label: "ART",                  type: "text" },
  { key: "tipo",                 label: "Tipo",                 type: "text" },
  { key: "participacao_tecnica", label: "Participação Técnica", type: "text", inList: false },
  { key: "forma_registro",       label: "Forma Registro",       type: "text", inList: false },
  { key: "pagamento",            label: "Pagamento",            type: "text" },
  { key: "taxa_paga",            label: "Taxa Paga",            type: "text", inList: false },
  { key: "cadastro",             label: "Cadastro",             type: "text" },
  { key: "observacao",           label: "Observação",           type: "textarea", full: true, inList: false },
  { key: "contratante",          label: "Contratante",          type: "text" },
  { key: "cnpj_contratante",     label: "CNPJ Contratante",     type: "text", inList: false },
  { key: "proprietario",         label: "Proprietário",         type: "text", inList: false },
  { key: "cnpj_proprietario",    label: "CNPJ Proprietário",    type: "text", inList: false },
  { key: "numero",               label: "Número",               type: "text" },
  { key: "valor_contrato",       label: "Valor Contrato",       type: "number" },
  { key: "data_inicio",          label: "Data Início",          type: "date" },
  { key: "data_fim",             label: "Data Fim",             type: "date", inList: false },
  { key: "enderecos",            label: "Endereços",            type: "textarea", full: true, inList: false },
  { key: "atividades",           label: "Atividades",           type: "textarea", full: true, inList: false },
  { key: "nivel",                label: "Nível",                type: "text", inList: false },
  { key: "atividade_subordinada",label: "Ativ. Subordinada",    type: "text", inList: false },
  { key: "atividade_servico",    label: "Ativ./Serviço",        type: "text", inList: false },
  { key: "quantidade",           label: "Quantidade",           type: "number", inList: false },
  { key: "unidade_medida",       label: "Unidade",              type: "text", inList: false },
];
