import type { FieldSchema } from "@/modules/engenharia/ui/crud/types";

/** Relatório Gerencial de Serviços (crea_gov_servicos) */
export const SERVICOS_FIELDS: FieldSchema[] = [
  { key: "numero",      label: "Número",       type: "text" },
  { key: "detalhe",     label: "Detalhe",      type: "textarea", full: true },
  { key: "analise",     label: "Análise",      type: "text" },
  { key: "baixa",       label: "Baixa",        type: "text" },
  { key: "boleto",      label: "Boleto",       type: "text" },
  { key: "pagamento",   label: "Pagamento",    type: "text" },
  { key: "cadastro",    label: "Cadastro",     type: "text" },
  { key: "empresa",     label: "Empresa",      type: "text" },
  { key: "contratante", label: "Contratante",  type: "text" },
  { key: "endereco",    label: "Endereço",     type: "textarea", full: true, inList: false },
  { key: "observacao",  label: "Observação",   type: "textarea", full: true, inList: false },
];

/** ARTs (Todas) — listagem completa exportada do SITAC/CREA (mesmas 11 colunas de SERVICOS) */
export const ARTS_TODAS_FIELDS: FieldSchema[] = [
  { key: "numero",      label: "Número",       type: "text" },
  { key: "detalhe",     label: "Detalhe",      type: "textarea", full: true },
  { key: "analise",     label: "Análise",      type: "text" },
  { key: "baixa",       label: "Baixa",        type: "text" },
  { key: "boleto",      label: "Boleto",       type: "text" },
  { key: "pagamento",   label: "Pagamento",    type: "text" },
  { key: "cadastro",    label: "Cadastro",     type: "text" },
  { key: "empresa",     label: "Empresa",      type: "text" },
  { key: "contratante", label: "Contratante",  type: "text" },
  { key: "endereco",    label: "Endereço",     type: "textarea", full: true, inList: false },
  { key: "observacao",  label: "Observação",   type: "textarea", full: true, inList: false },
];

/** ART por Bloco (crea_gov_art_bloco) — ordem e labels conforme planilha modelo "ARTs" (53 colunas) */
export const ART_BLOCO_FIELDS: FieldSchema[] = [
  { key: "numero_art",            label: "Número da ART",                          type: "text" },
  { key: "valor_art",             label: "Valor da ART",                           type: "number" },
  { key: "valor_pago",            label: "Valor pago",                             type: "number", inList: false },
  { key: "nosso_numero",          label: "Nosso número",                           type: "text", inList: false },
  { key: "registrada_em",         label: "Registrada em",                          type: "text", inList: false },
  { key: "paginas_pdf",           label: "Páginas do PDF",                         type: "text", inList: false },
  { key: "tipo_status_documento", label: "Tipo/Status documento",                  type: "text", inList: false },
  { key: "responsavel_tecnico",   label: "Responsável técnico",                    type: "text" },
  { key: "titulo_profissional",   label: "Título profissional",                    type: "text", inList: false },
  { key: "rnp",                   label: "RNP",                                    type: "text", inList: false },
  { key: "registro",              label: "Registro",                               type: "text", inList: false },
  { key: "contratante",           label: "Contratante",                            type: "text" },
  { key: "cpf_cnpj_contratante",  label: "CPF/CNPJ contratante",                   type: "text", inList: false },
  { key: "endereco_contrato",     label: "Endereço contrato",                      type: "text", inList: false },
  { key: "num_contrato_endereco", label: "Nº contrato endereço",                   type: "text", inList: false },
  { key: "complemento_contrato",  label: "Complemento contrato",                   type: "text", inList: false },
  { key: "cidade_contrato",       label: "Cidade contrato",                        type: "text", inList: false },
  { key: "bairro_contrato",       label: "Bairro contrato",                        type: "text", inList: false },
  { key: "uf_contrato",           label: "UF contrato",                            type: "text", inList: false },
  { key: "cep_contrato",          label: "CEP contrato",                           type: "text", inList: false },
  { key: "contrato",              label: "Contrato",                               type: "text", inList: false },
  { key: "celebrado_em",          label: "Celebrado em",                           type: "text", inList: false },
  { key: "valor_contrato",        label: "Valor contrato",                         type: "number", inList: false },
  { key: "tipo_contratante",      label: "Tipo de contratante",                    type: "text", inList: false },
  { key: "acao_institucional",    label: "Ação institucional",                     type: "text", inList: false },
  { key: "situacao",              label: "Situação",                               type: "text" },
  { key: "atendido",              label: "Atendido",                               type: "text", inList: false },
  { key: "data_solicitacao",      label: "Data da solicitação",                    type: "text", inList: false },
  { key: "data_atendimento",      label: "Data do atendimento",                    type: "text", inList: false },
  { key: "motivo",                label: "Motivo",                                 type: "textarea", full: true, inList: false },
  { key: "endereco_obra",         label: "Endereço obra/serviço",                  type: "text", inList: false },
  { key: "num_obra",              label: "Nº obra/serviço",                        type: "text", inList: false },
  { key: "complemento_obra",      label: "Complemento obra/serviço",               type: "text", inList: false },
  { key: "cidade_obra",           label: "Cidade obra/serviço",                    type: "text", inList: false },
  { key: "bairro_obra",           label: "Bairro obra/serviço",                    type: "text", inList: false },
  { key: "uf_obra",               label: "UF obra/serviço",                        type: "text", inList: false },
  { key: "cep_obra",              label: "CEP obra/serviço",                       type: "text", inList: false },
  { key: "data_inicio",           label: "Data de início",                         type: "text" },
  { key: "previsao_termino",      label: "Previsão de término",                    type: "text", inList: false },
  { key: "coordenadas",           label: "Coordenadas",                            type: "text", inList: false },
  { key: "codigo",                label: "Código",                                 type: "text", inList: false },
  { key: "cnpj_cpf_proprietario", label: "CNPJ/CPF proprietário",                  type: "text", inList: false },
  { key: "finalidade",            label: "Finalidade",                             type: "text", inList: false },
  { key: "proprietario",          label: "Proprietário",                           type: "text", inList: false },
  { key: "ativ_tec_numeros_atos", label: "Atividade técnica - números e #ATOS",    type: "text", inList: false },
  { key: "ativ_tec_quantidade",   label: "Atividade técnica - quantidade",         type: "text", inList: false },
  { key: "ativ_tec_unidade",      label: "Atividade técnica - unidade",            type: "text", inList: false },
  { key: "ativ_tec_descricao",    label: "Atividade técnica - descrição completa", type: "textarea", full: true, inList: false },
  { key: "observacoes",           label: "Observações",                            type: "textarea", full: true, inList: false },
  { key: "declaracoes",           label: "Declarações",                            type: "textarea", full: true, inList: false },
  { key: "entidade_classe",       label: "Entidade de classe",                     type: "text", inList: false },
  { key: "assinaturas",           label: "Assinaturas",                            type: "textarea", full: true, inList: false },
  { key: "informacoes",           label: "Informações",                            type: "textarea", full: true, inList: false },
];

/** Relatórios CREA (crea_gov_relatorio_crea) */
export const RELATORIO_CREA_FIELDS: FieldSchema[] = [
  { key: "art",                  label: "ART",                  type: "text" },
  { key: "tipo",                 label: "Tipo",                 type: "text" },
  { key: "participacao_tecnica", label: "Participação Técnica", type: "text", inList: false },
  { key: "forma_registro",       label: "Forma Registro",       type: "text", inList: false },
  { key: "pagamento",            label: "Pagamento",            type: "text" },
  { key: "taxa_paga",            label: "Taxa Paga",            type: "text", inList: false },
  { key: "cadastro",             label: "Cadastro",             type: "text" },
  { key: "observacao",           label: "Observação",           type: "textarea", full: true, inList: false },
  { key: "contratante",          label: "Contratante",          type: "text" },
  { key: "cnpj_contratante",     label: "CNPJ Contratante",     type: "text", inList: false },
  { key: "proprietario",         label: "Proprietário",         type: "text", inList: false },
  { key: "cnpj_proprietario",    label: "CNPJ Proprietário",    type: "text", inList: false },
  { key: "numero",               label: "Número",               type: "text" },
  { key: "valor_contrato",       label: "Valor Contrato",       type: "number" },
  { key: "data_inicio",          label: "Data Início",          type: "date" },
  { key: "data_fim",             label: "Data Fim",             type: "date", inList: false },
  { key: "enderecos",            label: "Endereços",            type: "textarea", full: true, inList: false },
  { key: "atividades",           label: "Atividades",           type: "textarea", full: true, inList: false },
  { key: "nivel",                label: "Nível",                type: "text", inList: false },
  { key: "atividade_subordinada",label: "Ativ. Subordinada",    type: "text", inList: false },
  { key: "atividade_servico",    label: "Ativ./Serviço",        type: "text", inList: false },
  { key: "quantidade",           label: "Quantidade",           type: "number", inList: false },
  { key: "unidade_medida",       label: "Unidade",              type: "text", inList: false },
];
