import type { FieldSchema } from "@/modules/engenharia/ui/crud/types";

/** Relatório Gerencial de Serviços (crea_gov_servicos) — ordem fixa conforme planilha CREA-PB (23 colunas).
 *  Ordem: ART, Tipo, Participação Técnica, Forma de Registro, Pagamento, Taxa Paga, Cadastro,
 *  Observação, Contratante:, CNPJ do contratante:, proprietário, CNPJ do proprietario, numero,
 *  valor do contrato:, data de inicio:, data de fim:, endereços, atividades, nível,
 *  atividade subordinada, atividade/serviço, quantidade, unidade de medida. */
export const SERVICOS_FIELDS: FieldSchema[] = [
  { key: "art",                   label: "ART",                    type: "text",
    aliases: ["art:","numero art","número art","número da art","numero da art","n art"] },
  { key: "tipo",                  label: "Tipo",                   type: "text",
    aliases: ["tipo:","tipo art","tipo da art"] },
  { key: "participacao_tecnica",  label: "Participação Técnica",   type: "text",
    aliases: ["participacao tecnica","participação tecnica","participacao técnica"] },
  { key: "forma_registro",        label: "Forma de Registro",      type: "text",
    aliases: ["forma registro","forma de registro:"] },
  { key: "pagamento",             label: "Pagamento",              type: "text",
    aliases: ["pagamento:","data pagamento","data de pagamento","pago em"] },
  { key: "taxa_paga",             label: "Taxa Paga",              type: "text",
    aliases: ["taxa","valor taxa","valor da taxa","taxa paga:"] },
  { key: "cadastro",              label: "Cadastro",               type: "text",
    aliases: ["cadastro:","data cadastro","data de cadastro","emitido em","registrado em"] },
  { key: "observacao",            label: "Observação",             type: "textarea", full: true,
    aliases: ["observacao","obs","observacoes","observações","observação:"] },
  { key: "contratante",           label: "Contratante",            type: "text",
    aliases: ["contratante:","cliente","tomador"] },
  { key: "cnpj_contratante",      label: "CNPJ do contratante",    type: "text",
    aliases: ["cnpj contratante","cnpj do contratante:","cnpj/cpf contratante","cpf cnpj contratante"] },
  { key: "proprietario",          label: "Proprietário",           type: "text",
    aliases: ["proprietario","proprietário:","proprietario:","empresa","razao social","razão social"] },
  { key: "cnpj_proprietario",     label: "CNPJ do proprietario",   type: "text",
    aliases: ["cnpj proprietario","cnpj do proprietário","cnpj/cpf proprietario","cpf cnpj proprietario"] },
  { key: "numero",                label: "Número",                 type: "text",
    aliases: ["numero","numero:","número:","numero contrato","numero do contrato","nº contrato"] },
  { key: "valor_contrato",        label: "Valor do contrato",      type: "number",
    aliases: ["valor contrato","valor do contrato:","valor"] },
  { key: "data_inicio",           label: "Data de início",         type: "text",
    aliases: ["data inicio","data de inicio:","início","inicio"] },
  { key: "data_fim",              label: "Data de fim",            type: "text",
    aliases: ["data fim","data de fim:","fim","termino","término"] },
  { key: "endereco",              label: "Endereços",              type: "textarea", full: true,
    aliases: ["enderecos","endereço","endereços:","endereco","local"] },
  { key: "atividades",            label: "Atividades",             type: "textarea", full: true,
    aliases: ["atividade","atividades:","atividades técnicas","atividades tecnicas"] },
  { key: "nivel",                 label: "Nível",                  type: "text",
    aliases: ["nivel","nível:","nivel:"] },
  { key: "atividade_subordinada", label: "Atividade subordinada",  type: "text",
    aliases: ["ativ subordinada","atividade subordinada:"] },
  { key: "atividade_servico",     label: "Atividade/Serviço",      type: "text",
    aliases: ["atividade servico","atividade/servico","ativ/servico","ativ./serviço"] },
  { key: "quantidade",            label: "Quantidade",             type: "number",
    aliases: ["qtd","qtde","quantidade:"] },
  { key: "unidade_medida",        label: "Unidade de medida",      type: "text",
    aliases: ["unidade","un","unid","unidade de medida:"] },
];

/** ARTs (Todas) — listagem completa exportada do SITAC/CREA.
 *  Ordem fixa conforme planilha modelo: Número, Detalhe, Análise, Baixa, Boleto,
 *  Pagamento, Cadastro, Empresa, Contratante, Endereço, Observação. */
export const ARTS_TODAS_FIELDS: FieldSchema[] = [
  { key: "numero",      label: "Número",       type: "text",
    aliases: ["art","n art","numero art","número da art","numero da art"] },
  { key: "detalhe",     label: "Detalhe",      type: "textarea", full: true,
    aliases: ["descricao","descrição","atividades","atividade/serviço","atividade servico"] },
  { key: "analise",     label: "Análise",      type: "text",
    aliases: ["status","situacao","situação","status analise","status análise"] },
  { key: "baixa",       label: "Baixa",        type: "text" },
  { key: "boleto",      label: "Boleto",       type: "text",
    aliases: ["numero boleto","número boleto","nosso numero","nosso número"] },
  { key: "pagamento",   label: "Pagamento",    type: "text",
    aliases: ["data pagamento","data de pagamento","pago em"] },
  { key: "cadastro",    label: "Cadastro",     type: "text",
    aliases: ["data cadastro","data de cadastro","emitido em","registrado em"] },
  { key: "empresa",     label: "Empresa",      type: "text",
    aliases: [
      "proprietario","proprietário","proprietario:","proprietário:",
      "razao social","razão social","razao_social","razão_social",
      "nome empresa","nome da empresa","empresa:","empresa contratada",
      "executora","contratado","contratada","responsavel","responsável",
    ] },
  { key: "contratante", label: "Contratante",  type: "text",
    aliases: ["contratante:","cliente","tomador"] },
  { key: "endereco",    label: "Endereço",     type: "textarea", full: true,
    aliases: ["enderecos","endereços","endereço:","local"] },
  { key: "observacao",  label: "Observação",   type: "textarea", full: true,
    aliases: ["obs","observacoes","observações"] },
];

/** ART por Bloco (crea_gov_art_bloco) — ordem e labels conforme planilha modelo "ARTs" (53 colunas) */
export const ART_BLOCO_FIELDS: FieldSchema[] = [
  { key: "numero_art",            label: "Número da ART",                          type: "text" },
  { key: "valor_art",             label: "Valor da ART",                           type: "number" },
  { key: "valor_pago",            label: "Valor pago",                             type: "number", inList: false },
  { key: "nosso_numero",          label: "Nosso número",                           type: "text", inList: false },
  { key: "registrada_em",         label: "Registrada em",                          type: "text", inList: false },
  { key: "paginas_pdf",           label: "Páginas do PDF",                         type: "text", inList: false },
  { key: "tipo_status_documento", label: "Tipo/Status documento",                  type: "text", inList: false },
  { key: "responsavel_tecnico",   label: "Responsável técnico",                    type: "text" },
  { key: "titulo_profissional",   label: "Título profissional",                    type: "text", inList: false },
  { key: "rnp",                   label: "RNP",                                    type: "text", inList: false },
  { key: "registro",              label: "Registro",                               type: "text", inList: false },
  { key: "contratante",           label: "Contratante",                            type: "text" },
  { key: "cpf_cnpj_contratante",  label: "CPF/CNPJ contratante",                   type: "text", inList: false },
  { key: "endereco_contrato",     label: "Endereço contrato",                      type: "text", inList: false },
  { key: "num_contrato_endereco", label: "Nº contrato endereço",                   type: "text", inList: false },
  { key: "complemento_contrato",  label: "Complemento contrato",                   type: "text", inList: false },
  { key: "cidade_contrato",       label: "Cidade contrato",                        type: "text", inList: false },
  { key: "bairro_contrato",       label: "Bairro contrato",                        type: "text", inList: false },
  { key: "uf_contrato",           label: "UF contrato",                            type: "text", inList: false },
  { key: "cep_contrato",          label: "CEP contrato",                           type: "text", inList: false },
  { key: "contrato",              label: "Contrato",                               type: "text", inList: false },
  { key: "celebrado_em",          label: "Celebrado em",                           type: "text", inList: false },
  { key: "valor_contrato",        label: "Valor contrato",                         type: "number", inList: false },
  { key: "tipo_contratante",      label: "Tipo de contratante",                    type: "text", inList: false },
  { key: "acao_institucional",    label: "Ação institucional",                     type: "text", inList: false },
  { key: "situacao",              label: "Situação",                               type: "text" },
  { key: "atendido",              label: "Atendido",                               type: "text", inList: false },
  { key: "data_solicitacao",      label: "Data da solicitação",                    type: "text", inList: false },
  { key: "data_atendimento",      label: "Data do atendimento",                    type: "text", inList: false },
  { key: "motivo",                label: "Motivo",                                 type: "textarea", full: true, inList: false },
  { key: "endereco_obra",         label: "Endereço obra/serviço",                  type: "text", inList: false },
  { key: "num_obra",              label: "Nº obra/serviço",                        type: "text", inList: false },
  { key: "complemento_obra",      label: "Complemento obra/serviço",               type: "text", inList: false },
  { key: "cidade_obra",           label: "Cidade obra/serviço",                    type: "text", inList: false },
  { key: "bairro_obra",           label: "Bairro obra/serviço",                    type: "text", inList: false },
  { key: "uf_obra",               label: "UF obra/serviço",                        type: "text", inList: false },
  { key: "cep_obra",              label: "CEP obra/serviço",                       type: "text", inList: false },
  { key: "data_inicio",           label: "Data de início",                         type: "text" },
  { key: "previsao_termino",      label: "Previsão de término",                    type: "text", inList: false },
  { key: "coordenadas",           label: "Coordenadas",                            type: "text", inList: false },
  { key: "codigo",                label: "Código",                                 type: "text", inList: false },
  { key: "cnpj_cpf_proprietario", label: "CNPJ/CPF proprietário",                  type: "text", inList: false },
  { key: "finalidade",            label: "Finalidade",                             type: "text", inList: false },
  { key: "proprietario",          label: "Proprietário",                           type: "text", inList: false },
  { key: "ativ_tec_numeros_atos", label: "Atividade técnica - números e #ATOS",    type: "text", inList: false },
  { key: "ativ_tec_quantidade",   label: "Atividade técnica - quantidade",         type: "text", inList: false },
  { key: "ativ_tec_unidade",      label: "Atividade técnica - unidade",            type: "text", inList: false },
  { key: "ativ_tec_descricao",    label: "Atividade técnica - descrição completa", type: "textarea", full: true, inList: false },
  { key: "observacoes",           label: "Observações",                            type: "textarea", full: true, inList: false },
  { key: "declaracoes",           label: "Declarações",                            type: "textarea", full: true, inList: false },
  { key: "entidade_classe",       label: "Entidade de classe",                     type: "text", inList: false },
  { key: "assinaturas",           label: "Assinaturas",                            type: "textarea", full: true, inList: false },
  { key: "informacoes",           label: "Informações",                            type: "textarea", full: true, inList: false },
];

/** Relatórios CREA (crea_gov_relatorio_crea) */
export const RELATORIO_CREA_FIELDS: FieldSchema[] = [
  { key: "art",                  label: "ART",                  type: "text" },
  { key: "tipo",                 label: "Tipo",                 type: "text" },
  { key: "participacao_tecnica", label: "Participação Técnica", type: "text", inList: false },
  { key: "forma_registro",       label: "Forma Registro",       type: "text", inList: false },
  { key: "pagamento",            label: "Pagamento",            type: "text" },
  { key: "taxa_paga",            label: "Taxa Paga",            type: "text", inList: false },
  { key: "cadastro",             label: "Cadastro",             type: "text" },
  { key: "observacao",           label: "Observação",           type: "textarea", full: true, inList: false },
  { key: "contratante",          label: "Contratante",          type: "text" },
  { key: "cnpj_contratante",     label: "CNPJ Contratante",     type: "text", inList: false },
  { key: "proprietario",         label: "Proprietário",         type: "text", inList: false },
  { key: "cnpj_proprietario",    label: "CNPJ Proprietário",    type: "text", inList: false },
  { key: "numero",               label: "Número",               type: "text" },
  { key: "valor_contrato",       label: "Valor Contrato",       type: "number" },
  { key: "data_inicio",          label: "Data Início",          type: "date" },
  { key: "data_fim",             label: "Data Fim",             type: "date", inList: false },
  { key: "enderecos",            label: "Endereços",            type: "textarea", full: true, inList: false },
  { key: "atividades",           label: "Atividades",           type: "textarea", full: true, inList: false },
  { key: "nivel",                label: "Nível",                type: "text", inList: false },
  { key: "atividade_subordinada",label: "Ativ. Subordinada",    type: "text", inList: false },
  { key: "atividade_servico",    label: "Ativ./Serviço",        type: "text", inList: false },
  { key: "quantidade",           label: "Quantidade",           type: "number", inList: false },
  { key: "unidade_medida",       label: "Unidade",              type: "text", inList: false },
];
